# See: https://taskfile.dev/api/

version: "3"

tasks:
  sso:
    cmds:
      - go run ./cmd/sso --config=./config/local.yaml
  migrate:
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  test:
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
      - go test -v ./tests

